### ISSUE TITLE
SPIKE — Design - work out what steps will be in the task list

### ISSUE THREAD

**Issue by Darren-CheckPlanningData** [digital-land/submit.planning.data.gov.uk#164]
Description:

To help us inform technical designs and have confidence the built system will behave as intended.

Objectives

Document the different states for the task list (not provided, issues, errors, etc)
Document whether different datasets require different tasks
Document the steps for each state

Scope

For each of the 8 datasets required for the ODP programme create a tasklist for the lifecycle of providing and updating a dataset

Acceptance criteria

- We have documented the different states required for the task list
- We have documented the steps for each of the states for the task list
- We have a flow diagram that describes how the task list should work
- We have discuss this with the infrastructure team

Timebox

2 days

Tasks

- [x] Work out scope for this work
- [x] Set up discussion between Paris & Alex to discuss direction
- [ ] Agree outputs / direction with Swati & Steve (as design will impact DM work with LPAs)
- [ ] Review outputs with infrastructure

**Comment by Darren-CheckPlanningData** [comment]
Designs for consideration

![Image](https://github.com/user-attachments/assets/2bec0fd4-9f28-47e4-92b3-db172c95043f)


![Image](https://github.com/user-attachments/assets/f6b43213-2ed7-4a8b-a29d-425b41a30418)


![Image](https://github.com/user-attachments/assets/c250326a-612b-45e7-ab70-b8bdd6ae5983)


![Image](https://github.com/user-attachments/assets/a03bbdc4-836a-40f5-8d6e-fed091491ba2)


![Image](https://github.com/user-attachments/assets/f2a80412-8f31-4fe4-8825-348d578cf512)
